### ISSUE TITLE
bintrayUpload fails due to invalid  dynamic version number in generated POM file

### ISSUE THREAD

**Issue by kuniss** [oehme/sobula#3]
If using the bintray-release plugin version 0.6.3 the [travis build](https://travis-ci.org/kuniss/XtendFlow/builds/82773207) fails for dynamic version dependencies like 

```
dependencies {
  compile 'org.eclipse.xtend:org.eclipse.xtend.lib:2.8.+'
}
```

with the following error:

```
Execution failed for task ':bintrayUpload'.

> Could not sync 'kuniss/maven/de.grammarcraft.xtend.flow/0.4.2' to Maven Central: HTTP/1.1 400 Bad Request [messages:[Invalid POM: /de/grammarcraft/de.grammarcraft.xtend.flow/0.4.2/de.grammarcraft.xtend.flow-0.4.2.pom: Project name missing, Invalid version for Dependency {groupId=org.eclipse.xtend, artifactId=org.eclipse.xtend.lib, version=2.8.+, type=jar} - uses invalid dynamic version syntax.

  Replace with a fixed version or standard mathematical notation e.g., [1.5,) for version 1.5 and higher., Dropping existing partial staging repository.], status:Validation Failed]
```

The  used Gradle build file may be inspected [here](https://github.com/kuniss/XtendFlow/blob/ce50d6cf96e98f06051b13b4069827ea86c7ca63/FlowDesignInXtend-ActiveAnnotations/build.gradle).

It worked with plugin version 0.4.3; not sure whether it worked with 0.5.0.

**Comment by oehme** [comment]
Yes, that is expected. I no longer use the resolved-dependencies-plugin from Netflix. This has two reasons:
- it broke compatibility with Gradle 2.3+
- it would replace any version range with a simple version number, which might be pretty unexpected

So if you want to upload to a Maven repo, you need to use Maven-style version ranges.

**Comment by kuniss** [comment]
Thanks for the note.

Do you mean I would have to substitute the dynamic dependency
'org.eclipse.xtend:org.eclipse.xtend.lib:2.8.+' by the equivalent of
'org.eclipse.xtend:org.eclipse.xtend.lib:[2.8,2.9)'?

Am 29.09.2015 um 21:29 schrieb Stefan Oehme:

**Comment by oehme** [comment]
Yes, exactly.

2015-09-29 22:02 GMT+02:00 Denis Kuniß notifications@github.com:

**Comment by kuniss** [comment]
After having switched to non-dynamic versions I'm still getting an error on publishing to MavenCentral:

```
Execution failed for task ':bintrayUpload'.

> Could not sync 'kuniss/maven/de.grammarcraft.xtend.flow/0.4.3' to Maven Central: HTTP/1.1 400 Bad Request [messages:[Invalid POM: /de/grammarcraft/de.grammarcraft.xtend.flow/0.4.3/de.grammarcraft.xtend.flow-0.4.3.pom: Project name missing, Dropping existing partial staging repository.], status:Validation Failed]
```

Did I missed somewhere to set the project name?

**Comment by oehme** [comment]
Nope, my fault, I'll fix that right away

2015-09-30 11:04 GMT+02:00 Denis Kuniß notifications@github.com:

**Comment by oehme** [comment]
Fixed in 0.6.4, should be in the plugin central soon

2015-09-30 11:26 GMT+02:00 Stefan Oehme st.oehme@gmail.com:

**Comment by kuniss** [comment]
Great! 
Thanks again for the plugin! Very helpful.
I will try the new version as it will be available.

**Comment by kuniss** [comment]
... Works well now. :relaxed:
